import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import {Locale, NextIntlClientProvider} from 'next-intl';
import {inter, yekan} from "../lib/font";

const geistSans = Geist({
  variable: "--fonts-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--fonts-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
                                           children,
                                           params
                                         }: {
  children: React.ReactNode;
  params: Promise<{locale: Locale}>
}) {

  const {locale} = await params;
  const fontClass =
      locale === "fa"
          ? yekan.className
          : inter.className;
  return (
      <div
          className={fontClass}
          dir={locale === "fa" ? "rtl" : "ltr"}
      >
        {children}
      </div>

  );
}