import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import {Locale, NextIntlClientProvider} from 'next-intl';
import {inter, yekan} from "@/lib/font";
import Navbar from "@/components/layout/navbar/navbar";
import {getTranslations} from "next-intl/server";
import NavbarLinks from "@/components/layout/navbar/navbar-links";
import Footer from "@/components/sections/footer/footer";

const geistSans = Geist({
  variable: "--fonts-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--fonts-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
                                           children,
                                           params
                                         }: {
  children: React.ReactNode;
  params: Promise<{locale: Locale}>
}) {

  const {locale} = await params;
  const fontClass =
      locale === "fa"
          ? yekan.className
          : inter.className;

    const t = await getTranslations("Navbar");

    const labels = {
        home: t("home"),
        about: t("about"),
        services: t("services"),
        projects: t("projects"),
        blog: t("blog"),
        contact: t("contact"),
    };

  return (
      <NextIntlClientProvider>
      <div
          className={`${fontClass}`}
          dir={locale === "fa" ? "rtl" : "ltr"}
      >
          <Navbar
              labels={labels}
              cta={t("cta")}
          />
          <div className={'bg-white'}>
              {children}
          </div>
          <Footer />
      </div>
      </NextIntlClientProvider>

  );
}